### ISSUE TITLE
Stupid build needs optimized

### ISSUE THREAD

**Issue by dylanPowers** [WSU-ACM/hackathon-site#40]
Building and deploying takes way too long.
Brainstorming:
* The deploy could probably be sped up by throwing the build into a tarball (no need to compress it). The individual file processing of scp is killing us.
* The build seems to access npm every time build is ran...no need for that.
* Image compression should be done once and then committed into the repo.
* I fucking hate Handlebars because it crashes randomly (okay that can't really be fixed haha)

**Comment by techfreek** [comment]
* It shouldn't be too hard to create a tarball from the files
* I think part of the reason it does that is because every time I try to build the site without doing `rm -rf build/` so it was necessary to re-install it. 
* I'm okay with the image compression. I am just trying to think of a decent way to do it when we add more images
* Yeah, I have no clue what is going on with handlebars. I'm no help there

**Comment by techfreek** [comment]
Also, while I agree these need to be optimized, I think that it can wait. I have too much on my plate to take care of before the hackathon. If you can tackle it, be my guest. I personally won't get a chance until after.

**Comment by dylanPowers** [comment]
Dunzo!
