### ISSUE TITLE
Get back to the basics? 

### ISSUE THREAD

**Issue by t-walker** [WSU-ACM/hackathon-site#50]
It's taken me over an hour so far to get it up and going and it's still not done. For as simple as this website should be, and the fact it needs to last longer than we do I feel like we should consider streamlining it into something that takes one or two commands to get going.

**Comment by whyrusleeping** [comment]
i mean, its a webpage that has some text and some pictures on it. It should be static. (which means you could deploy it with ipfs :D )

**Comment by t-walker** [comment]
:D

**Comment by t-walker** [comment]
I don't really think we need as many APIs as we have and I'd rather it take me 10 minutes to clone repo -> make changes -> push changes. 

Also, maybe a CSS framework?

**Comment by whyrusleeping** [comment]
what APIs are there? its an informational page, you should just be able to throw it behind apache and serve it off disk.

**Comment by t-walker** [comment]
+1

**Comment by techfreek** [comment]
I think some of the complexities came from a desire to have a site template so we didn't have to update each page when we changed the navbar or something like that. I would still recommend tempting to save your selves time and effort, but you may want to take it back to the drawing board.

**Comment by t-walker** [comment]
I think having a jekyll site is fine but it should be much more minimal.

**Comment by techfreek** [comment]
I can agree with that. The one note, is there are a few pages with dynamic
content (ie the teams page and the pictures page). So make sure you account
for that.

**Comment by dylanPowers** [comment]
It's dirt simple once you get the dependencies set up. I finally have time, so I'll create a docker image for it.

**Comment by whyrusleeping** [comment]
yay dockerrrrrr

**Comment by dylanPowers** [comment]
Fuuuuuckckckckckckckckcckckck node!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I think I found your problem Tyler. One of the node dependencies is completely fucked. And because npm doesn't keep track of working versions (like the far superior dartlang's pub lol), I get to start forking and hunting down version numbers that work. I think I'd rather just rip out this stupid [sharp](https://github.com/lovell/sharp) library.

**Comment by dylanPowers** [comment]
Javascript land makes me feel like I'm working in a sewer where my job is to clear the shit blockage and no matter how good that shit flows, it's still really shitty.

**Comment by dylanPowers** [comment]
@t-walker + everyone, try https://github.com/dylanPowers/hackathon-site/tree/docker.

Once you get docker and docker-compose set up, you should be able to simply run:
`docker-compose up` and it should Just Work™

**Comment by techfreek** [comment]
Yeah, one thing I'll admit about npm is it will only update when it you specifically tell it to update. I know of a few packages that haven't updated the package on npm, but are actively developing. Kinda annoying.

If you are able to find an image library that doesn't require image size info, feel free to take out sharp, but right now we need someway to measure image sizes and it's the fastest library I found for that.

**Comment by dylanPowers** [comment]
@techfreek I was talking about having a .lock file. Both ruby gem and dart pub use it. It's a file checked into version control that gives an exact version to each dependency so you don't have to go tracking down version numbers when something breaks. In npm, if someone clones your repo and runs npm install, it isn't guaranteed they'll download the same exact dependencies as you. In dart and ruby however, there is that guarantee. 
With that out of the way, I finally got the sharp library compiling correctly. In this instance Docker is very nice. There are still three steps to getting everything running, but it's at least mostly guaranteed to work without a hitch. I may jump into the package.json file and lock down every dependency there.                                       
I still have to update the docs in the wiki, but @t-walker would you call this issue closed? As of d3d7d4ac12766b20d39e0d0e313b18e8d4e9afb3 everything is merged.

**Comment by t-walker** [comment]
I'll review later; but I still think that we need to work on a simpler solution. My goal is that we should be able to put someone in 121 w/ HTML experience in front of this code and have them make changes. Currently, that doesn't seem like a thing.

**Comment by whyrusleeping** [comment]
hey guys. we dont need nodejs.js for a static website.

**Comment by t-walker** [comment]
I honestly think we need to mimic what we have in a new site with bootstrap or some other CSS framework. This project is significantly more complicated than it should be. Currently only one person has the know-how to quickly make changes and down the line that's just not going to work.

I'm chill with using Jekyll for templating purposes but beyond that we don't need APIs or anything that fancy. If we're that concerned about serving pictures we should be using a 3rd party hosting solution (flickr, etc.) and using a JS plugin.

**Comment by t-walker** [comment]
Docker and Node are cool and all but, this needs to be kept lightweight not only so we can have people edit it now but down the line when others continue to run this.

**Comment by dylanPowers** [comment]
We don't need bootstrap or any other CSS framework...because they don't really provide anything useful. CSS4 is good enough. We're not even using sass which I'm actually surprised by.
For the images I really wanted to link into the facebook album, but I didn't find any good drop in solutions for doing that. This api may be able to grab what we need: [https://developers.facebook.com/docs/graph-api/reference/v2.5/album]. However I've never used Facebook's apis, so idk.
As it currently stands, if we remove the pictures page, the entirety of node can be ripped out.

**Comment by t-walker** [comment]
I would rather this stays open. 

We need to find a better solution than what we've got. After this year's hackathon we will likely revert back to a static HTML website.

**Comment by dylanPowers** [comment]
Tyler, I'm sorry but I don't know what you want???? A completely static site is a very unrealistic goal and very messy. Implementing the site that way would be utter garbage and I don't work in shit. The Jekyll build is very simple (every github page/wiki uses it). The go api is very simple as it's ~200 lines + go is highly readable, unless you don't want pictures on the website??????
So no, this is staying closed as long as I'm working on this.

**Comment by whyrusleeping** [comment]
static sites arent unrealistic!!! https://www.youtube.com/watch?v=fVSu_t0CsWA

**Comment by dylanPowers** [comment]
Jeromy you're confusing completely static (what Tyler is thinking) vs a statically built site (what is currently implemented). The site as it is is technically "static" except for the image hosting which I thought I'd just offload to Facebook to simplify things. I could have the pictures statically loaded but that would require more work that I prefer to have Facebook do for me ;)

**Comment by whyrusleeping** [comment]
a static site doesnt have an api server though.

**Comment by dylanPowers** [comment]
:facepalm: Yes! That's why I said "except for the image hosting"

**Comment by whyrusleeping** [comment]
whats so much work about statically loading pictures?

**Comment by dylanPowers** [comment]
That there's 500 pictures and I'd have to either work in the generation of
the picture links into the build or have a dynamic "build" script that
would watch the Facebook api for changes and write that to disk, but at
that point whether nginx or the go server serves up the file, does it
really matter? It's getting pedantic at that point considering serving the
website over ipfs or other distributed systems isn't one of our goals.

**Comment by whyrusleeping** [comment]
thats not the point. The point is to reduce the complexity of the codebase so future hackathon planners can easily work on it. having to install docker, set up facebook api tokens, learn docker to make any changes, and then learn whatever we're using for the server thing that talks to facebook is a lot of effort for an overworked student who is donating their time to help make the hackathon happen.

**Comment by dylanPowers** [comment]
Ugh you guys are frustrating me. I'm hearing a bunch of griping without any solutions. Like seriously, has anybody bothered to understand why everything exists as it does????? Everything is there for a purpose. 
There are literally 3 steps to get running: https://github.com/WSU-ACM/hackathon-site/wiki/build-instructions#development

"having to install docker" ah man that's so hard dude. Following step by step instructions that I link to in the documentation is pretty damn difficult.
"set up facebook api tokens" Ah man, asking Dylan for a string and putting that into a file is soooo difficult.
"learn docker to make any changes" Not really. Unless you need a new system dependency? You shouldn't even have to touch the dockerfile. The hard parts have been solved. Any type of build or deployment system is going to have a learning curve no matter what you choose. Remove docker? Well now at the very least you have to know how to properly set up an nginx server, and install jekyll. Oh and I hope you installed the right versions. Mmmm, so much fun (not really next to installing docker).
"learn whatever we're using for the server thing that talks to facebook" That will only be touched if you need to add a new album, but I can make that even simpler to do of course. Too lazy to even bother doing that? Remove the pictures page. And no I'm not going to throw all those pictures into git. Only an idiot would do that.

**Comment by dylanPowers** [comment]
An example solution that no one has stated: Why don't we deploy this as a Github page Dylan? That's super simple.
Yes, example person. That is super simple. For one, we haven't done that because we wanted a pictures page and photo albums are naturally dynamic. We often add photos over the course of the hackathon. Secondly, there are historical reasons. Many of us that have worked on the website in the past are very curious about new technologies, learning, and like writing code. We wanted to host everything ourselves because we embraced the challenge and thought it was fun. 
I'd be open to that, but I really like having the photos available to those not on Facebook, and manually managing all of those photos through the tools available to a github page would be a pain. Why would it be a pain you ask? Because each photo would have to be added by hand either in html directly, or in some json file.

**Comment by 21CamBam** [comment]
This is Cammi chiming in.

I realize it sucks to have people criticizing your work. It feels like people are shitting all over what you worked so hard to create, But this is the whole group asking you to make a change. You don't fight them, you don't get mad and lash out, you adapt. That's what engineers do. If they aren't giving you solutions, it's because you should be exploring the solutions. If you've already done that research and there is absolutely no other way but yours, no simpler way to maintain the website then write something up that explains why each possible solution won't work. Try not to get so defensive and never give ultimatums. Part of working together as a team is receiving feedback and doing what you can to incorporate that feedback and if you can't, explain calmly why not.

Frankly, I tried to deploy a dummy change to make sure that someone else, anyone else with no knowledge of the tool, can do it and it didn't work for me. I couldn't even get the change to post on the local server web page. If you are really passionate about using docker, then make your wiki clearer. If you want specifics on what needs to be clearer, we'll give them to you. For example, have a whole subsection on making changes and deploying them. Don't depend on the docker wiki to get people setup. The whole point of a wiki is so that someone, after you are long graduated, can read it once and know exactly what you know about the system. For all you know, after we're all gone, the new hackathon committee might put some 121 student in charge of the website. If you need help and are too busy, tell someone and you get the help.

**Comment by dylanPowers** [comment]
I'm taking this to facebook for some privacy on the matter
